AllCops:
  Exclude:
    - db/schema.rb
    - ./bin/**/*
  RunRailsCops: true
Documentation:
  Enabled: false
Metrics/AbcSize:
  Exclude:
    - ./**/db/**/*.rb
Metrics/LineLength:
  Exclude:
    - Guardfile
  Max: 120
Metrics/MethodLength:
  Exclude:
    - ./**/db/**/*.rb
Style/ClassAndModuleChildren:
  Exclude:
    - ./**/app/controllers/**/*.rb
    - ./**/app/models/**/*.rb
    - ./**/spec/**/*.rb